// ignore_for_file: constant_identifier_names

enum Span {
  FIXED_SPAN_AB_1,
  SIMPLE_SPAN_AB_1,
  FIXED_SPAN_BC_1,
  SIMPLE_SPAN_BC_1,

  FIXED_SPAN_AB_2,
  SIMPLE_SPAN_AB_2,
  FIXED_SPAN_BC_2,
  SIMPLE_SPAN_BC_2,

  FIXED_SPAN_AB_3,
  SIMPLE_SPAN_AB_3,
  FIXED_SPAN_BC_3,
  SIMPLE_SPAN_BC_3,

  FIXED_SPAN_AB_4,
  SIMPLE_SPAN_AB_4,
  FIXED_SPAN_BC_4,
  SIMPLE_SPAN_BC_4,

  FIXED_SPAN_AB_5,
  SIMPLE_SPAN_AB_5,
  FIXED_SPAN_BC_5,
  SIMPLE_SPAN_BC_5,

  FIXED_SPAN_AB_6__1,
  SIMPLE_SPAN_AB_6__1,
  FIXED_SPAN_BC_6__1,
  SIMPLE_SPAN_BC_6__1,

  FIXED_SPAN_AB_6__2,
  SIMPLE_SPAN_AB_6__2,
  FIXED_SPAN_BC_6__2,
  SIMPLE_SPAN_BC_6__2,
  
  FIXED_SPAN_AB_7__1,
  SIMPLE_SPAN_AB_7__1,
  FIXED_SPAN_BC_7__1,
  SIMPLE_SPAN_BC_7__1,

  FIXED_SPAN_AB_7__2,
  SIMPLE_SPAN_AB_7__2,
  FIXED_SPAN_BC_7__2,
  SIMPLE_SPAN_BC_7__2,

  FIXED_SPAN_AB_8,
  SIMPLE_SPAN_AB_8,
  FIXED_SPAN_BC_8,
  SIMPLE_SPAN_BC_8,

  FIXED_SPAN_AB_9,
  SIMPLE_SPAN_AB_9,
  FIXED_SPAN_BC_9,
  SIMPLE_SPAN_BC_9,

  FIXED_SPAN_AB_10__1,
  SIMPLE_SPAN_AB_10__1,
  FIXED_SPAN_BC_10__1,
  SIMPLE_SPAN_BC_10__1,

  FIXED_SPAN_AB_10__2,
  SIMPLE_SPAN_AB_10__2,
  FIXED_SPAN_BC_10__2,
  SIMPLE_SPAN_BC_10__2,

  FIXED_SPAN_AB_11,
  SIMPLE_SPAN_AB_11,
  FIXED_SPAN_BC_11,
  SIMPLE_SPAN_BC_11,

  FIXED_SPAN_AB_12,
  SIMPLE_SPAN_AB_12,
  FIXED_SPAN_BC_12,
  SIMPLE_SPAN_BC_12,

  FIXED_SPAN_AB_13__1,
  SIMPLE_SPAN_AB_13__1,
  FIXED_SPAN_BC_13__1,
  SIMPLE_SPAN_BC_13__1,

  FIXED_SPAN_AB_13__2,
  SIMPLE_SPAN_AB_13__2,
  FIXED_SPAN_BC_13__2,
  SIMPLE_SPAN_BC_13__2,

  FIXED_SPAN_AB_14__1,
  SIMPLE_SPAN_AB_14__1,
  FIXED_SPAN_BC_14__1,
  SIMPLE_SPAN_BC_14__1,

  FIXED_SPAN_AB_14__2,
  SIMPLE_SPAN_AB_14__2,
  FIXED_SPAN_BC_14__2,
  SIMPLE_SPAN_BC_14__2,

  FIXED_SPAN_AB_15__1,
  SIMPLE_SPAN_AB_15__1,
  FIXED_SPAN_BC_15__1,
  SIMPLE_SPAN_BC_15__1,

  FIXED_SPAN_AB_15__2,
  SIMPLE_SPAN_AB_15__2,
  FIXED_SPAN_BC_15__2,
  SIMPLE_SPAN_BC_15__2,

  FIXED_SPAN_AB_16__1,
  SIMPLE_SPAN_AB_16__1,
  FIXED_SPAN_BC_16__1,
  SIMPLE_SPAN_BC_16__1,

  FIXED_SPAN_AB_16__2,
  SIMPLE_SPAN_AB_16__2,
  FIXED_SPAN_BC_16__2,
  SIMPLE_SPAN_BC_16__2,

  FIXED_SPAN_AB_17__1,
  SIMPLE_SPAN_AB_17__1,
  FIXED_SPAN_BC_17__1,
  SIMPLE_SPAN_BC_17__1,
  
  FIXED_SPAN_AB_17__2,
  SIMPLE_SPAN_AB_17__2,
  FIXED_SPAN_BC_17__2,
  SIMPLE_SPAN_BC_17__2,

  FIXED_SPAN_AB_18, 
  SIMPLE_SPAN_AB_18,
  FIXED_SPAN_BC_18,
  SIMPLE_SPAN_BC_18,
}

enum Loading {
  loading1Combination,
  loading2Combination,
  loading5Combination,
  loading7Combination,
  loading17Combination,
  loading18Combination,
}